// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc771.Mildread2015;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveLeftMotor;
    public static SpeedController driveRightMotor;
    public static RobotDrive driveRobotDrive;
    public static AnalogInput driveLeftRange;
    public static AnalogInput driveRightRange;
    public static SpeedController elevatorElevatorMotor;
    public static DigitalInput elevatorLowerLimitSwitch;
    public static DigitalInput elevatorUpperLimitSwitch;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveLeftMotor = new Talon(1);
        LiveWindow.addActuator("Drive", "LeftMotor", (Talon) driveLeftMotor);
        
        driveRightMotor = new Talon(2);
        LiveWindow.addActuator("Drive", "RightMotor", (Talon) driveRightMotor);
        
        driveRobotDrive = new RobotDrive(driveLeftMotor, driveRightMotor);
        
        driveRobotDrive.setSafetyEnabled(true);
        driveRobotDrive.setExpiration(0.1);
        driveRobotDrive.setSensitivity(0.5);
        driveRobotDrive.setMaxOutput(1.0);
        driveRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        driveLeftRange = new AnalogInput(1);
        LiveWindow.addSensor("Drive", "LeftRange", driveLeftRange);
        
        driveRightRange = new AnalogInput(2);
        LiveWindow.addSensor("Drive", "RightRange", driveRightRange);
        
        elevatorElevatorMotor = new Talon(3);
        LiveWindow.addActuator("Elevator", "ElevatorMotor", (Talon) elevatorElevatorMotor);
        
        elevatorLowerLimitSwitch = new DigitalInput(0);
        LiveWindow.addSensor("Elevator", "LowerLimitSwitch", elevatorLowerLimitSwitch);
        
        elevatorUpperLimitSwitch = new DigitalInput(1);
        LiveWindow.addSensor("Elevator", "UpperLimitSwitch", elevatorUpperLimitSwitch);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
